name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"    # كل 10 دقائق (UTC)
  workflow_dispatch: {}        # تشغيل يدوي عند الحاجة

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PING_URL secret exists
        run: |
          if [ -z "${{ secrets.PING_URL }}" ]; then
            echo "PING_URL secret is missing. Add it in GitHub -> Settings -> Secrets -> Actions."
            exit 1
          fi

      - name: Random small delay (avoid hitting with UptimeRobot at same second)
        run: sleep $((RANDOM % 40))

      - name: Primary ping (with retries)
        run: |
          URL="${{ secrets.PING_URL }}"
          echo "Pinging $URL ..."
          ping() {
            curl -sS -L \
              --connect-timeout 10 \
              --max-time 45 \
              --retry 6 \
              --retry-delay 5 \
              --retry-connrefused \
              -H "User-Agent: KeepAliveBot/1.0 (+github-actions)" \
              -H "Cache-Control: no-cache" \
              -o /dev/null \
              -w "HTTP %{http_code}\n" \
              "$1"
          }
          CODE=$(ping "$URL" | tail -n1 | awk '{print $2}')
          echo "Primary response: HTTP ${CODE:-unknown}"
          if [ -z "$CODE" ] || [ "$CODE" -lt 200 ] || [ "$CODE" -ge 400 ]; then
            echo "Primary ping not clearly successful. Will try fallback..."
            exit 2
          fi

      - name: Fallback ping (root path) if primary failed
        if: failure()
        run: |
          ROOT_URL="${{ secrets.BACKUP_URL }}"
          if [ -z "$ROOT_URL" ]; then
            ROOT_URL="$(echo "${{ secrets.PING_URL }}" | sed 's#/healthz$#/#')"
          fi
          echo "Pinging fallback: $ROOT_URL ..."
          curl -sS -L \
            --connect-timeout 10 \
            --max-time 60 \
            --retry 7 \
            --retry-delay 5 \
            --retry-connrefused \
            -H "User-Agent: KeepAliveBot/1.0 (+github-actions)" \
            -H "Cache-Control: no-cache" \
            -o /dev/null \
            -w "HTTP %{http_code}\n" \
            "$ROOT_URL"
